;;; custom-vars.el --- Custom Variables & Faces -*- lexical-binding: t; -*-
;;; Commentary:
;; This file stores custom-set-variables and custom-set-faces, usually generated by Emacs.

;;; Code:

;; =============================================================================
;; 9. Custom Variables & Faces
;; =============================================================================

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 '(package-selected-packages
   '(lua-mode deft org-roam org-download org-bullets vterm slime-volleyball
     slime posframe org-modern exec-path-from-shell doom-themes auctex)))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 '(org-level-1 ((t (:inherit default :weight bold :height 1.3))))
 '(org-level-2 ((t (:inherit default :weight bold :height 1.2))))
 '(org-level-3 ((t (:inherit default :weight bold :height 1.1)))))

(provide 'custom-vars)
;;; custom-vars.el ends here
